// --- CSAPAT ADATOK ---
const LEAGUES = {
    'Premier League': [
        { name: 'Manchester City', strength: 95, color: '#6CABDD', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/382.png' },
        { name: 'Arsenal', strength: 93, color: '#EF0107', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/359.png' },
        { name: 'Liverpool', strength: 92, color: '#C8102E', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/364.png' },
        { name: 'Chelsea', strength: 89, color: '#034694', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/363.png' },
        { name: 'Tottenham Hotspur', strength: 88, color: '#132257', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/367.png' },
        { name: 'Manchester Utd', strength: 87, color: '#DA291C', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/360.png' },
        { name: 'Newcastle Utd', strength: 86, color: '#241F20', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/361.png' },
        { name: 'Aston Villa', strength: 85, color: '#670E36', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/362.png' },
        { name: 'Brighton', strength: 83, color: '#0057B8', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/331.png' },
        { name: 'West Ham Utd', strength: 82, color: '#7A263A', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/371.png' },
        { name: 'Everton', strength: 81, color: '#003399', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/368.png' },
        { name: 'Wolverhampton', strength: 80, color: '#FDB913', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/380.png' },
        { name: 'Fulham', strength: 79, color: '#CCCCCC', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/370.png' },
        { name: 'Crystal Palace', strength: 78, color: '#1B458F', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/384.png' },
        { name: 'Brentford', strength: 77, color: '#C70000', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/337.png' },
        { name: 'Bournemouth', strength: 76, color: '#B50024', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/346.png' },
        { name: 'Nottingham Forest', strength: 75, color: '#DD0000', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/349.png' },
        { name: 'Ipswich Town', strength: 73, color: '#003399', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/366.png' },
        { name: 'Leicester City', strength: 74, color: '#0053A0', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/375.png' },
        { name: 'Southampton', strength: 72, color: '#D71920', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/376.png' },
    ],
    'Championship': [
        { name: 'Leeds United', strength: 78, color: '#FFCD00', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/357.png' },
        { name: 'Burnley', strength: 77, color: '#6C1D45', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/379.png' },
        { name: 'Watford', strength: 76, color: '#FBEE23', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/394.png' },
        { name: 'Sheffield Utd', strength: 75, color: '#EE2737', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/334.png' },
        { name: 'Norwich City', strength: 74, color: '#00A65D', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/381.png' },
        { name: 'West Brom', strength: 73, color: '#002F65', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/373.png' },
        { name: 'Middlesbrough', strength: 72, color: '#E11B22', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/378.png' },
    ],
    'La Liga': [
        { name: 'Real Madrid', strength: 96, color: '#FEBE10', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/86.png' },
        { name: 'FC Barcelona', strength: 90, color: '#A50044', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/83.png' },
        { name: 'Atlético Madrid', strength: 88, color: '#CB3524', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/106.png' },
        { name: 'Sevilla', strength: 85, color: '#D31414', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/243.png' },
        { name: 'Villarreal', strength: 84, color: '#005995', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/257.png' },
        { name: 'Real Sociedad', strength: 83, color: '#0E73BC', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/244.png' },
        { name: 'Athletic Bilbao', strength: 82, color: '#E4002B', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/84.png' },
        { name: 'Valencia', strength: 80, color: '#F6872D', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/249.png' },
        { name: 'Real Betis', strength: 79, color: '#00A35B', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/242.png' },
    ],
    'Bundesliga': [
        { name: 'Bayern München', strength: 94, color: '#DC052D', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/132.png' },
        { name: 'Borussia Dortmund', strength: 90, color: '#FDE100', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/124.png' },
        { name: 'Bayer Leverkusen', strength: 92, color: '#E32221', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/129.png' },
        { name: 'RB Leipzig', strength: 87, color: '#001C46', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/127.png' },
        { name: 'Eintracht Frankfurt', strength: 85, color: '#D80000', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/130.png' },
    ],
    '2. Bundesliga': [
        { name: 'Schalke 04', strength: 78, color: '#004D9D', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/137.png' },
        { name: 'Hamburger SV', strength: 77, color: '#0054A6', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/123.png' },
        { name: 'Hertha BSC', strength: 76, color: '#0054A6', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/139.png' },
    ],
    'Serie A': [
        { name: 'Juventus', strength: 91, color: '#FFFFFF', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/111.png' },
        { name: 'AC Milan', strength: 90, color: '#FB090B', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/103.png' },
        { name: 'Inter Milan', strength: 89, color: '#0055A0', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/110.png' },
        { name: 'Napoli', strength: 88, color: '#007FFF', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/120.png' },
        { name: 'Roma', strength: 86, color: '#8E0013', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/102.png' },
    ],
    'Ligue 1': [
        { name: 'PSG', strength: 95, color: '#004171', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/144.png' },
        { name: 'Marseille', strength: 87, color: '#002F6C', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/142.png' },
        { name: 'Monaco', strength: 85, color: '#CE1126', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/145.png' },
        { name: 'Lille', strength: 82, color: '#E2021A', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/143.png' },
        { name: 'Lyon', strength: 81, color: '#003893', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/146.png' },
    ],
    'NB I': [
        { name: 'Ferencváros', strength: 75, color: '#006633', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6902.png' },
        { name: 'Puskás Akadémia', strength: 72, color: '#1B3079', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6854.png' },
        { name: 'Fehérvár FC', strength: 70, color: '#C8010C', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/3141.png' },
        { name: 'Debreceni VSC', strength: 68, color: '#880D11', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6855.png' },
        { name: 'Diósgyőri VTK', strength: 67, color: '#A60000', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6856.png' },
        { name: 'Zalaegerszegi TE', strength: 66, color: '#0054A6', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6857.png' },
        { name: 'Újpest FC', strength: 65, color: '#562D7E', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6858.png' },
        { name: 'Kecskeméti TE', strength: 64, color: '#4B0082', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6859.png' },
        { name: 'Paks', strength: 63, color: '#009C4C', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6860.png' },
        { name: 'Kisvárda', strength: 62, color: '#003366', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6861.png' },
        { name: 'MTK Budapest', strength: 60, color: '#003366', logo: 'https://a.espncdn.com/i/teamlogos/soccer/500/6862.png' },
        { name: 'Nyíregyháza', strength: 58, color: '#D50032', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Ny%C3%ADregyh%C3%A1za_Spartacus_FC_logo.svg/200px-Ny%C3%ADregyh%C3%A1za_Spartacus_FC_logo.svg.png' },
    ],
};
